---
- name: set fact force_install to no
  set_fact: force_install=no

- name: set fact force_install to yes
  set_fact: force_install=yes
  when: kibana_allow_downgrades

- name: Ensure dependency is installed (Ubuntu).
  apt: name=apt-transport-https state=present

- name: Add Elasticsearch apt key.
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Kibana repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ kibana_major_version }}/apt stable main'
    state: present
    update_cache: true

- name: Debian - Ensure elasticsearch is installed
  become: yes
  apt:
    name: '{{ kibana_package_name }}{% if kibana_version is defined %}={{ kibana_version }}{% endif %}'
    state: present
    force: '{{ force_install }}'
    cache_valid_time: 86400
  notify: restart kibana